apiVersion: v1
kind: Secret
metadata:
  name: {{ include "btg-node.fullname" . }}-rpcsecret
  labels:
    {{- include "btg-node.labels" . | nindent 4 }}
data:
  rpcuser: {{ randAlphaNum 8 | b64enc | quote }}
  rpcpass: {{ randAlphaNum 32 | b64enc | quote }}
